name: Atilio Stone Design LLC 
url: atiliostonedesignerllc.com
markdown: redcarpet
rouge: pygments
excerpt_separator: <!--more-->
plugins:
  - jekyll-paginate
paginate: 5
paginate: 3
paginate_path: "blog/page:num"
